hmcts/sscs-cor-frontend

app/controllers/question.js, app/locale/en.json, app/views/layout.html, app/views/question.html, test/browser/question.test.js, test/mock/data/question.js, test/page-objects/base.js, test/unit/controllers/question.test.js
- Display question body on page
- Add body to response to controller
- Add mock body content
- Add unit tests and functional tests
- Add back link
- Add phase banner
=> [PREVIEW] SSCS-3569 Display question body

app/assets/sass/_question.scss, app/locale/en.json, app/views/question.html, package.json, test/accessibility/runPa11y.js, test/browser/question.test.js, test/page-objects/base.js
- Add textarea to the question page
- Add content and styling
- Add test
=> [PREVIEW] SSCS-3719 question field

Jenkinsfile_CNP, app/middleware/health.js, config/custom-environment-variables.json, config/test.json, infrastructure/main.tf, package.json, test/browser/common.js, test/browser/hello-world.test.js, test/browser/question.test.js, test/fixtures/coh.js, test/mock/data/health.js, test/page-objects/question.js, test/unit/middleware/health.test.js, yarn.lock
* bootstrapping data on the COH API, create online hearing, create a question, issue round
* adding COH URL to the config and configuring the COH_URL env var in required pipeline stages
* re-enabling question page tests, now running using stubs locally and real services on preview/AAT
* moving some packages to dev dependencies
* running hello-world test as smoke, for now, to prevent creating any data on prod
* configuring connection to backend and adding API status to health check
=> [PREVIEW] Real functional testing

test/unit/app-insights.test.js, test/unit/services/getQuestion.test.js
- Write test for app insights enable function
=> App insights unit test

app/controllers/question.js, app/services/postAnswer.js, test/browser/question.test.js, test/mock/services/answer.js, test/mock/services/question.js, test/unit/controllers/question.test.js, test/unit/services/postAnswer.test.js
- Modify the save answer functionality to match the response from the api
- Remove localhost test
=> [PREVIEW] SSCS-3570 Modiy save answer api response

app/assets/sass/_task-list.scss, app/assets/sass/application.scss, app/controllers/question.js, app/controllers/taskList.js, app/locale/en.json, app/routes.js, app/services/getAllQuestions.js, app/views/question.html, app/views/task-list.html, test/browser/common.js, test/browser/question.test.js, test/browser/task-list.test.js, test/fixtures/coh.js, test/mock/services/allQuestions.js, test/page-objects/task-list.js, test/unit/controllers/question.test.js, test/unit/controllers/taskList.test.js, test/unit/services/getAllQuestions.test.js
- Add page that lists all the questions
=> [PREVIEW] SSCS-3557 questions list

app/views/task-list.html, test/mock/services/allQuestions.js, test/unit/controllers/taskList.test.js, test/unit/services/getAllQuestions.test.js
=> SSCS-3557 Changed answer states to be be the SSCS values not COH values

app/controllers/question.js, app/routes.js, app/views/includes/sending-evidence.html
* this only works if a user is "signed in"
* otherwise the same default number is shown
* some bits will need to be amended once we have implemented auth properly using IDAM
=> SSCS-3736 Showing the user specific SC number in sending evidence guidance

README.md, create-test-data.ts, package.json, test/browser/bootstrap.ts, test/browser/common.ts
* can now be done using a yarn command
* instructions added in README
=> [PREVIEW] Separating out data bootstrap to allow others to easily create test data

README.md, create-test-data.ts, package.json
add yarn command
format console log
=> Console log formating

package.json, test/fixtures/ccd.js
test[0-9]+@hmcts.net this has been setup in TYA-notifications
to not send real emails. If yuo want to send real emails you will
need an email address which has been setup on gov notify.
=> Set the email address in the test data we create to match

.dockerignore, Dockerfile, config/docker.json, docker-compose.yml, package.json
I setup this up last night as my backup machine didn't have correct node version or redis installed
=> add docker

app/server/controllers/extend-deadline.ts, app/server/controllers/task-list.ts, app/server/locale/en.json, app/server/views/extend-deadline/contact-tribunal.html, app/server/views/extend-deadline/index.html, test/browser/2-extend-deadline.test.ts, test/mock/cor-backend/services/all-questions.js, test/mock/cor-backend/services/deadline.js, test/unit/controllers/extend-deadline.test.ts, test/unit/services/getAllQuestions.test.ts
Appellant is shown a static page with contact details if trying for a second extension
=> [PREVIEW] Second deadline extension attempt

app/server/controllers/tribunal-view.ts, app/server/routes.ts, app/server/services/getOnlineHearing.ts, locale/en.json, nodemon.json, test/browser/4-tribunal-view.test.ts, test/mock/cor-backend/services/hearing.js, test/unit/controllers/decision.test.ts, test/unit/controllers/tribunal-view.test.ts, views/tribunal-view.html
Update tribunal view template.  Radio selection logic to be added in separate pull request
=> [PREVIEW] Add radios to tribunal view

test/browser/4-tribunal-view.test.ts
* this is due to COH failing to issue notifications
* as soon as COH is fixed, this should be reverted
=> Only run functional tests for tribunal view locally

README.md, app/server/controllers/hearing-confirm.ts, app/server/controllers/tribunal-view.ts, app/server/paths.ts, app/server/routes.ts, app/server/utils/fieldValidation.ts, locale/en.json, test/browser/2-extend-deadline.test.ts, test/browser/3-question.test.ts, test/browser/4-tribunal-view.test.ts, test/browser/5-request-hearing.test.ts, test/browser/bootstrap.ts, test/browser/common.ts, test/fixtures/ccd.ts, test/fixtures/coh.ts, test/page-objects/hearing-confirm.ts, test/unit/controllers/hearing-confirm.test.ts, test/unit/utils/field-validation.test.ts, views/extend-deadline/confirmation-no.html, views/extend-deadline/confirmation-yes.html, views/extend-deadline/contact-tribunal.html, views/hearing-confirm/index.html, views/question/index.html, views/questions-completed.html
Prototype: https://sscs-cor.herokuapp.com/mvp/hearing-confirm
=> [PREVIEW]  Confirm new hearing page

app/server/controllers/tribunal-view.ts, app/server/routes.ts, app/server/services/tribunalView.ts, test/browser/4-tribunal-view.test.ts, test/browser/5-request-hearing.test.ts, test/mock/cor-backend/services/tribunal-view.js, test/unit/controllers/tribunal-view.test.ts, test/unit/services/idamService.test.ts, test/unit/services/tribunalView.test.ts
* call backend service to record acceptance of tribunal's view
* fixing formatting and nock stub on idamService
=> [PREVIEW] SSCS-3588 record acceptance

locale/en.json, test/browser/2-extend-deadline.test.ts, test/browser/4-tribunal-view.test.ts, test/browser/5-request-hearing.test.ts, views/dummy-login.html, views/extend-deadline/index.html, views/hearing-confirm/index.html, views/hearing-why/index.html, views/question/index.html, views/tribunal-view.html
* header of "There are errors on the page"
* sub-header of "Please fix the errors before you continue"
=> Amending all the error summary elements to display the correct content

app/server/controllers/hearing-why.ts, app/server/controllers/questions-completed.ts, app/server/controllers/task-list.ts, test/browser/2-extend-deadline.test.ts, test/browser/3-question.test.ts, test/browser/4-tribunal-view.test.ts, test/browser/5-request-hearing.test.ts, test/fixtures/coh.ts, test/integration/login.test.ts, test/mock/cor-backend/services/all-questions.js, test/mock/cor-backend/services/deadline.js, test/mock/cor-backend/services/hearing.js, test/mock/cor-backend/services/sumbit-answer.js, test/unit/controllers/decision.test.ts, test/unit/controllers/extend-deadline.test.ts, test/unit/controllers/hearing-confirm.test.ts, test/unit/controllers/hearing-why.test.ts, test/unit/controllers/question.test.ts, test/unit/controllers/questions-completed.test.ts, test/unit/controllers/task-list.test.ts, test/unit/controllers/tribunal-view-accepted.test.ts, test/unit/controllers/tribunal-view.test.ts, test/unit/services/extend-deadline.test.ts
* when creating a UTC date we don't need to execute the moment function first
* just need to do `moment.utc()`
=> Fixing moment UTC calls

app/server/controllers/tribunal-view-accepted.ts, app/server/controllers/tribunal-view.ts, app/server/middleware/check-decision.ts, app/server/services/getOnlineHearing.ts, test/browser/4-tribunal-view.test.ts, test/browser/common.ts, test/mock/coh/services/decision-issue.js, test/mock/cor-backend/services/hearing.js, test/mock/cor-backend/services/tribunal-view.js, test/unit/controllers/tribunal-view-accepted.test.ts, test/unit/controllers/tribunal-view.test.ts, test/unit/middleware/check-decision.test.ts
* for a user who has previously accepted the tribunal view and returns later
* amending check decision middleware to redirect user to that page if necessary
=> SSCS-4150 Showing user the view accepted page on return to the service

app/server/controllers/hearing-confirm.ts, app/server/controllers/hearing-why.ts, app/server/controllers/tribunal-view.ts, app/server/middleware/check-decision.ts, test/browser/5-request-hearing.test.ts, test/unit/controllers/hearing-confirm.test.ts, test/unit/controllers/hearing-why.test.ts, test/unit/middleware/check-decision.test.ts
* once a user has requested a hearing and given their reasons, if they sign-in again they see the same hearing booking page
* the response date is 6 weeks from the date they requested the hearing
=> SSCS-4169  Showing user hearing booking page if already requested a hearing

README.md, views/includes/head.html, views/layout.html
* script and noscript added
* updated README with overview of how the page view tracking is configured for multiple environments
=> SSCS-3792 Adding Google Tag Manager

app/client/sass/_question.scss, app/server/controllers/question.ts, test/browser/3-question.test.ts, test/mock/cor-backend/services/question.js, test/page-objects/base.ts, test/unit/controllers/question.test.ts, views/question/answer-form.html, views/question/evidence-list.html, views/question/sending-evidence.html
Implemented evidence listing
Tests are incomplete, as there inter-dependency with file upload story
=> Show list of uploaded evidence [tests incomplete]

README.md, app/server/controllers/question.ts, locale/en.json, package.json, test/browser/3-question.test.ts, test/page-objects/base.ts, test/page-objects/extend-deadline.ts, test/page-objects/hearing-confirm.ts, test/page-objects/hearing-why.ts, test/page-objects/tribunal-view.ts, test/page-objects/upload-evidence.ts, test/unit/controllers/question.test.ts, views/question/upload-evidence.html
* this is just a template, no upload processing is taking place yet, coming next
* requests will return 404 response if feature is not enabled or overridden
* some minor tidying also
=> SSCS-3595 Adding upload-evidence page (no upload yet)

app/client/sass/_question.scss, app/client/sass/application.scss, app/server/controllers/question.ts, locale/en.json, test/unit/controllers/question.test.ts, views/question/evidence-list.html, views/question/sending-evidence.html, views/question/upload-evidence.html
Basic templating, locale and scsss
=> Initial file delete work

app/server/controllers/question.ts, test/browser/3-question.test.ts, test/unit/controllers/question.test.ts, views/question/answer-form.html
* post question page and save answer to COH if one exists
* redirect to upload evidence page after optional save
* fix upload evidence section not showing on question page after validation errors found
=> SSCS-3595 Save draft answer when navigating to upload evidence page

app/server/controllers/question.ts, package.json, test/browser/3-question.test.ts, test/mock/cor-backend/services/evidence-remove.js, test/page-objects/question.ts, test/unit/controllers/question.test.ts
Fixed bug where app was hanging when we tried to delete evidence. The
call to delete was returning a function rather than executing the code.
=> SSCS-3650 Delete evidence

app/server/app.ts, app/server/middleware/health.ts, test/unit/middleware/health.test.ts
=> SSCS-4166 Health middleware changed to use request-promise

locale/en.json, views/question/upload-evidence.html
to upload on non javascript evidence upload page.
=> SSCS-4374 Add warning message that larger files may take a while

app/server/controllers/idam-stub.ts, views/login.html
Added some css style to the idam stub login page to make this look a
bit more professional when we show it to users.
=> SSCS-4377 Style login page

.dockerignore, Dockerfile, Jenkinsfile_CNP, kubernetes/deployment.template.yaml
Added setup to build docker images and deploy to AKS.
=> SSCS-4132 Setup AKS

sonar-project.properties
code coverage. Need to talk this through with a frontend dev when we
have one.
=> Exclude these files as Sonar has suddenly starting saying they have no

app/client/javascript/evidence-upload.ts, app/client/sass/_question.scss, locale/en.json, test/unit/client/javascript/evidence-upload.test.ts, views/question/answer-form.html
When uploading a file with Javascript enable show a spinner whilst
the file is being uploaded.
=> SSCS-4376 Add upload spinner

app/client/sass/application.scss, views/question/answer-form.html, views/submit-question.html
We made some links secondary buttons but they were too close to the
previous button. Add some padding.
=> SSCS-4424 Add padding between buttons

Jenkinsfile_CNP, README.md, config/custom-environment-variables.json, config/default.json, test/fixtures/coh.ts, test/fixtures/s2s.ts, test/mock/s2s/services/oauth2_authoirse.js, test/mock/s2s/services/oauth2_token.js
Need to set the Authorization when creating test data. This is done by
getting an access token. Have used fixed values for the user and
redirect url rather than a logged in user as this is for test data
before anyone has logged in.
=> SSCS-4248 Fix S2S for test data setup

locale/en.json, views/task-list.html
- Voice Over reads now correctly task list
- It reads now in the format "Question, state, List n of total" 
(e.g. How do you walk to the doctors?, Draft, List 2 of 2
Solves ticket https://tools.hmcts.net/jira/browse/SSCS-4600
=> Voice over reads correctly questions list

app/client/javascript/check-cookies.ts, app/client/javascript/main.ts, app/client/sass/_cookie-banner.scss, app/client/sass/application.scss, locale/en.json, test/unit/client/check-cookies.test.ts, views/includes/cookie-banner.html, views/layout.html
- Adding cookies blocked banner 
- This is step 1 of 2 
- When user's cookies are blocked display
- Step 2 would be creating cookie privacy page.
- Added relavent unit tests for JS functions
=> [SCSS-4589] cookie banner

sonar-project.properties
Include files previously excluded in Sonar once code coverage is working again
Fixes second part of https://tools.hmcts.net/jira/browse/SSCS-4536
Reverts PR #153
=> Include files in sonar project

app/client/javascript/check-cookies.ts
- Set cookie path to parent directory.
=> Set cookie path to parent directory.

.nycrc, yarn.lock
Updating Instanbul config file so temp files are created in the proper git ignored folder
=> Fix security vulnerabilities in node dependencies (#182)

locale/en.json, views/question/answer-form.html
- Prevent accessibility problem with using aria-label instead of hidden label.
- Changed label text with a request of Steven
Related Ticket : https://tools.hmcts.net/jira/browse/SSCS-4590
=> [SSCS-4590] Change hidden label to aria-label attribute.

views/policy-pages/cookie-privacy.html
- Added back button to cookie policy page.
- Clicking back button should take user to page user come from.
Sotry : https://tools.hmcts.net/jira/browse/SSCS-4826
=> Added back button to cookie page.

test/page-objects/base.ts, test/page-objects/question.ts
Refactor test for answering a really long question was using puppetter type function which was sending a keydown, keypress/input, and keyup event for each character in the text.
Created a new method so a value can be set without sending the above events
=> Refactor answering a long question test

app/client/sass/_decision.scss, app/server/app.ts, app/server/controllers/tribunal-view.ts, app/server/services/hearing.ts, locale/en.json, test/mock/cor-backend/services/hearing.js, test/unit/controllers/decision.test.ts, test/unit/controllers/hearing-confirm.test.ts, test/unit/controllers/hearing-why.test.ts, test/unit/controllers/tribunal-view-confirm.test.ts, test/unit/controllers/tribunal-view.test.ts, views/decision.html, views/tribunal-view.html
Now get back some more fields for the tribunal view page. Updated the
page to reflect what is in the prototype now we get all the data.
=> SSCS-4818 Preliminary View

views/login.html, views/question/answer-form.html
- This is part of https://tools.hmcts.net/jira/browse/SSCS-4825 
- Created a subticket 
- https://tools.hmcts.net/jira/browse/SSCS-4838
- Removed the autocomplete from login and answer inputs
=> Added autocomplete off

.nycrc, app/client/javascript/check-cookies.ts, app/client/javascript/evidence-upload.ts, app/client/javascript/expanding-textbox.ts, app/client/javascript/main.ts, package-lock.json, package.json, sonar-project.properties, test/browser/3-question.test.ts, test/unit/client/check-cookies.test.ts, test/unit/client/expanding-textbox.test.ts, test/unit/client/main.test.ts, test/unit/controllers/submit-question.test.ts, test/unit/routes.test.ts
- Improving code coverage
- Files added to sonar cloud initially excluded
- main.ts
- paths.ts
=> Improving code coverage and test other files excluded

app/client/sass/application.scss, test/mock/cor-backend/services/questionData.js, views/question/index.html
Update question view template so it can properly render questions from JUI using rich-text format
=> Update question view to accommodate HTML from JUI

.gitignore, locale/en.json, views/layout.html
- Content Change for the alpha phase banner.
- Survery link is still required.
=> [SSCS-4380] Content change phase banner.

app/client/javascript/check-cookies.ts, app/client/javascript/main.ts, test/unit/client/check-cookies.test.ts, test/unit/client/main.test.ts
Cookie Banner Class Refactor remove window parameters both from class and unit tests.
=> Refactoring cookie banner and refactoring unit tests

package.json, views/layout.html
Fixes favicon issues and also fixes default assets path for govuk elements.
=> Fixing govuk default asset path

app/server/app.ts
- To avoid zap problems removed wildcard Content Policy.
=> Removed wildcard policy

locale/en.json, views/tribunal-view.html
- Copy changes for table titles
- Add rules to display titles in case of empty activities
=> Copy changes and rules for empty activities

app/client/javascript/main.ts, locale/en.json, views/errors/500.html
Add Try again link to 500 error page
Add info paragraph before Contact Us block 
Solves SSCS-5083
=> Tech. difficulties screen - try again/back link

locale/en.json, test/unit/client/evidence-upload.test.ts
ticket: https://tools.hmcts.net/jira/browse/SSCS-5098
=> Changed evidence send address.

app/server/controllers/login.ts
=> Corrected register idam link looks like this is different between

app/server/utils/fieldValidation.ts, locale/en.json, test/browser/5-request-hearing.test.ts, test/unit/controllers/hearing-why.test.ts, test/unit/utils/field-validation.test.ts, views/hearing-why/form.html
Remove empty validation from hearing why text area
Add info label for the text area
=> Remove empty validation hearing why textarea

infrastructure/prod.tfvars
Trying to see if this is what is causing permission errors
=> Rolled back url changes for prod

app/server/utils/fieldValidation.ts, locale/en.json
Solves https://tools.hmcts.net/jira/browse/SSCS-5087
=> Add character limit to 20000 characters

locale/en.json, views/decision.html, views/errors/404.html, views/errors/500.html, views/extend-deadline/index.html, views/hearing-confirm/index.html, views/hearing-why/index.html, views/layout.html, views/load-case-error.html, views/login.html, views/policy-pages/cookie-privacy.html, views/question/index.html, views/question/upload-evidence.html, views/questions-completed.html, views/submit-question.html, views/task-list.html, views/tribunal-view-accepted.html, views/tribunal-view-confirm.html, views/tribunal-view.html
- Added exit links for the surverys.
- Added page header to each template to use as a parameter on exit links.
Ticket #247  https://tools.hmcts.net/jira/browse/SSCS-4380
=> Added exit link with page header parameters.

app/server/controllers/login.ts, locale/en.json, test/unit/controllers/login.test.ts, views/hearing-why/booking.html, views/tribunal-view-accepted.html
Added exit survery links for accepted and rejected decision pages
ticket #https://tools.hmcts.net/jira/browse/SSCS-5154
=> Added exit link for accepted and rejected decision pages.

app/client/sass/application.scss, views/tribunal-view.html
Add table header width
Cells top vertical align
Solves  https://tools.hmcts.net/jira/browse/SSCS-5084
=> Add preliminary view table columns style

app/server/watch.ts, test/unit/watch.test.ts
- Added unit tests for watch.ts
=> Added unit tests for watch.ts

Jenkinsfile_parameterized
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=926&view=detail&selectedIssue=SSCS-5182
Deploy frontend to sandbox environment
```
[ ] Yes
[ x] No
```
=> added file for sandbox

app/server/controllers/question.ts, app/server/utils/fieldValidation.ts, locale/en.json, test/browser/3-question.test.ts, test/unit/controllers/question.test.ts, test/unit/utils/field-validation.test.ts
- Added answer validation Logic on save
- Added new error message on save
- Updated validation messages regarding empty answer.
- Updated Unit tests.
Ticket #: https://tools.hmcts.net/jira/browse/SSCS-5198
=> SSCS-5198 Question page validation

app/server/controllers/tribunal-view-confirm.ts, app/server/utils/fieldValidation.ts, locale/en.json, test/browser/4-tribunal-view.test.ts, test/unit/controllers/tribunal-view-confirm.test.ts, test/unit/controllers/tribunal-view.test.ts, test/unit/utils/field-validation.test.ts
https://tools.hmcts.net/jira/browse/SSCS-5199
- Updated  validation message on PV confirmation step.
- Updated unit test.
=> SSCS-5199 Change validation message on PV confirm page.

locale/en.json
https://tools.hmcts.net/jira/browse/SSCS-5198
- fix the content
=> Align submit validation message with acceptance criteria.

app/client/javascript/evidence-upload.ts, app/client/javascript/expanding-textbox.ts, app/server/controllers/additional-info.ts, app/server/paths.ts, app/server/routes.ts, views/additional-info/evidence-options.html
- Created a shared structure for all additional info components.
- Typescript refactoring for  evidenceupload.ts and expanding-textbox.ts
=> SSCS-5273 Created folder and controller structure for additional info.

app/server/controllers/additional-evidence.ts, test/browser/2-0-additional-evidence.test.ts, test/page-objects/additional-evidence.ts, test/page-objects/base.ts, test/unit/controllers/additional-evidence.test.ts, views/additional-evidence/evidence-options.html, views/additional-evidence/index.html, views/task-list.html
https://tools.hmcts.net/jira/browse/SSCS-3565
Adding Unit and Functional tests for additional evidence options page
```
[ ] Yes
[ X ] No
```
=> Adding unit and functional tests to evidence options page

sonar-project.properties
Excluding test coverage files from sonar cloud
```
[ ] Yes
[ X ] No
```
=> Excluding test coverage files from sonar

sonar-project.properties
Sonar exclusions
```
[ ] Yes
[ X ] No
```
=> Sonar exclusions

sonar-project.properties
Exclude sonar test coverage dir
```
[ ] Yes
[ X ] No
```
=> Exclude sonar test dir

app/server/controllers/additional-evidence.ts, app/server/controllers/question.ts, app/server/utils/fieldValidation.ts
- Refactoring of answer and statement text validation process.
[ ] Yes
[X] No
=> Refactor answer , statement text validation process.

locale/en.json, views/additional-evidence/evidence-confirm.html, views/additional-evidence/evidence-options.html, views/additional-evidence/evidence-post.html, views/additional-evidence/evidence-statement.html, views/additional-evidence/evidence-upload.html, views/additional-evidence/index.html
https://tools.hmcts.net/jira/browse/SSCS-5348
Added confirmation page for additional evidence
=> Added additional evidence confirm page.

test/fixtures/sidam.ts
Add a log statement as we don't appear to be creating the user in the correct idam.
=> Get sidam working in aat

infrastructure/main.tf
We have added the s2s headers to the calls to the 
backend app so now we need to setup the url and 
secret to get the the header values.
=> Setup s2s environment variables

app/server/services/additional-evidence.ts
https://tools.hmcts.net/jira/browse/SSCS-3566
Amend BE save statement call method and body parameter
```
[ ] Yes
[ X ] No
```
=> Amend call for saving additional statement

app/client/sass/application.scss, app/server/controllers/additional-evidence.ts, app/server/services/additional-evidence.ts, app/server/utils/fieldValidation.ts, locale/en.json, test/mock/cor-backend/services/additional-evidence-statement.js, test/unit/controllers/additional-evidence.test.ts, test/unit/utils/field-validation.test.ts, views/additional-evidence/evidence-upload.html, views/additional-evidence/index.html
https://tools.hmcts.net/jira/browse/SSCS-3568
Additional evidence upload now has a description to describe the uploaded evidence. Also, an error is shown if either a description can't be found or no files are submitted.
```
[ ] Yes
[ X ] No
```
=> Adding description to additional evidence file upload

app/client/javascript/evidence-upload.ts, views/additional-evidence/evidence-upload.html, views/components/spinner.html, views/question/answer-form.html
Adding spinner on additional evidence upload page to inform appellant the file is being sent
```
[ ] Yes
[ X ] No
```
=> Additional evidence upload spinner

app/server/controllers/question.ts, test/unit/controllers/question.test.ts, test/unit/middleware/file-upload-validation.test.ts
Question controller refactoring to use (multer) file upload validation middleware, move logic in case of error to the corresponding controller function
```
[ ] Yes
[ X ] No
```
=> Refactoring Question controller to use file validation middleware

app/server/controllers/tribunal-view.ts, app/server/services/additional-evidence.ts, sonar-project.properties, test/unit/controllers/additional-evidence.test.ts, test/unit/services/additional-evidence.test.ts
Including files for Sonar tests. Adding unit tests for those files.
```
[ ] Yes
[ X ] No
```
=> Adding files to sonar and unit tests

Jenkinsfile_CNP, charts/sscs-cor-frontend/Chart.yaml, charts/sscs-cor-frontend/requirements.yaml, charts/sscs-cor-frontend/values.aat.template.yaml, charts/sscs-cor-frontend/values.preview.template.yaml, charts/sscs-cor-frontend/values.template.yaml
helm chart
```
[ ] Yes
[x] No
```
=> helm charts

test/browser/2-0-additional-evidence.test.ts, test/page-objects/additional-evidence-confirmation.ts, test/page-objects/additional-evidence-statement.ts, test/page-objects/additional-evidence-upload.ts
Adding functional tests for the additional evidence feature
```
[ ] Yes
[ X ] No
```
=> Adding functional tests for additional evidence

test/browser/2-0-additional-evidence.test.ts, test/page-objects/additional-evidence-confirmation.ts, test/page-objects/additional-evidence-post.ts, test/page-objects/additional-evidence-upload.ts, test/page-objects/base.ts
Adding more functional test for additional evidence feature
```
[ ] Yes
[ X ] No
```
=> Adding more functional tests

infrastructure/main.tf
Forcing app settings update 
```
[ ] Yes
[ X ] No
```
=> Forcing app settings update adding a new one setting

test/crossbrowser/helpers/SauceLabsReportingHelper.js, test/crossbrowser/saucelabs.conf.js
https://tools.hmcts.net/jira/browse/SSCS-5905
Migrating Saucelabs US DC to EU DC
```
[ ] Yes
[ X ] No
```
=> Migrating Saucelabs US DC to EU DC

config/test.json
Reducing timeout for crossbrowser tests
```
[ ] Yes
[ X ] No
```
=> Reducing waiting for text timeout

test/crossbrowser/helpers/SauceLabsReportingHelper.js
Reveal saucelabs credentials
```
[ ] Yes
[ X ] No
```
=> revealing saucelabs credentials

app/server/app.ts, app/server/utils/screenReaderUtils.ts, test/unit/utils/screenReaderUtils.ts, views/includes/appellant-details.html, views/question/answer-form.html
https://tools.hmcts.net/jira/browse/SSCS-5050
Improving screen reader readibility for long numbers
```
[ ] Yes
[ X ] No
```
=> Screen reader long numbers

app/client/javascript/detailsToggle.ts, test/unit/client/detailsToggle.test.ts
https://tools.hmcts.net/jira/browse/SSCS-5452
Refactoring tabindex attribute toggle for all children
```
[ ] Yes
[ X ] No
```
=> Toggle Tabindex attribute refactoring

app/client/sass/application.scss, app/server/controllers/your-details.ts, app/server/paths.ts, app/server/routes.ts, locale/en.json, test/unit/controllers/your-details.ts, views/includes/account-navigation.html, views/your-details.html
https://tools.hmcts.net/jira/browse/SSCS-5645
Adding new page 'your-details'
```
[ ] Yes
[ X ] No
```
=> Adding new page your-details

app/client/sass/_history-list.scss, app/client/sass/application.scss, app/server/app-configurations.ts, app/server/app.ts, app/server/controllers/history.ts, app/server/middleware/ensure-authenticated.ts, app/server/paths.ts, app/server/routes.ts, locale/en.json, test/mock/cor-backend/services/hearing.js, test/mock/tribunals/data/oral/dwpRespond.json, test/mock/tribunals/data/oral/hearing.json, test/mock/tribunals/data/oral/hearingBooked.json, test/mock/tribunals/services/getAppeal.js, test/unit/controllers/history.test.ts, views/components/panel.html, views/history.html, views/includes/mya-contact-us.html, views/status.html
https://tools.hmcts.net/jira/browse/SSCS-5640
Adding History page for MYA
```
[ ] Yes
[ X ] No
```
=> Add history page

app/client/sass/application.scss, app/server/app-configurations.ts, app/server/controllers/your-details.ts, locale/en.json, test/mock/cor-backend/services/citizen.js, test/unit/controllers/your-details.ts, views/your-details.html
https://tools.hmcts.net/jira/browse/SSCS-5645
Integrating appellant details endpoint and refactoring view to show details
```
[ ] Yes
[ X ] No
```
=> Your details integration

app/server/data/appealStages.ts
https://tools.hmcts.net/jira/browse/SSCS-5627
https://tools.hmcts.net/jira/browse/SSCS-5629
Mapping DORMANT event to hearing and decision status in status bar for oral and paper cases respectively.
```
[ ] Yes
[ X ] No
```
=> Mapping dormant stage to Decicion and Hearing bar status

views/your-details.html
https://tools.hmcts.net/jira/browse/SSCS-5645
Layout change to 2/3 full width
Increase margin for inset text
```
[ ] Yes
[ X ] No
```
=> Your details page refactoring

app/client/sass/application.scss, views/your-details.html
https://tools.hmcts.net/jira/browse/SSCS-5645
Columns on your-details page are now 50%
```
[ ] Yes
[ X ] No
```
=> Refactor columns width on your details page to 50%

app/server/controllers/hearing.ts, locale/en.json, test/mock/cor-backend/services/citizen.js, test/unit/controllers/hearing.test.ts, views/hearing-tab.html
https://tools.hmcts.net/jira/browse/SSCS-5997
- Complete hearing tab.
```
[ ] Yes
[X] No
```
=> Adding Hearing arrangements to hearing tab.

package.json, test/browser/6-mya.test.ts, test/browser/common.ts, test/fixtures/ccd.ts, test/mock/idam/services/login-page.js, test/mock/idam/services/login-redirect.js, test/mock/tribunals/data/oral/hearing.json, test/mock/tribunals/dysonSetup.js, test/mock/tribunals/server.js, test/page-objects/assign-case.ts, test/page-objects/base.ts, test/page-objects/status.ts
https://tools.hmcts.net/jira/browse/SSCS-6167
Adding first functional test for MYA feature, emulating 'assign case' journey for a user coming from SYA with no case associated to his/her idam user. 
```
[ ] Yes
[ X ] No
```
=> Adding first functional test for MYA feature

app/server/controllers/your-details.ts, locale/en.json, test/unit/controllers/your-details.ts, views/your-details.html
https://tools.hmcts.net/jira/browse/SSCS-6263
- Add name
- Fix Mobile and Phone
- Add to dictionary 
```
[ ] Yes
[X] No
```
=> Fix your details missing parts.

app/server/controllers/login.ts, locale/en.json, test/unit/controllers/login.test.ts, views/select-case.html
If the user has multiple case assigned to them, load a page which allows
them to select the case they wish to view in MYA.
https://tools.hmcts.net/jira/browse/SSCS-6104
```
[ ] Yes
[X] No
```
=> SSCS-5625 Allow user to select case to view

locale/en.json
https://tools.hmcts.net/jira/browse/SSCS-6262
Replace Contact Us link on Your Details page and tabs
```
[X] Yes
[ ] No
```
=> SSCS-6262 - Contact us hearing change.

app/client/sass/_web-chat.scss, app/client/sass/application.scss, app/server/app-configurations.ts, package.json, views/layout.html
Fix webchat path copy problem
```
[ ] Yes
[X] No
```
=> Fix copy path issue

app/server/controllers/assign-case.ts, locale/en.json, test/unit/controllers/assign-case.test.ts, views/assign-case/index.html
Corrected wording layout and error message on the assign-case page.
https://tools.hmcts.net/jira/browse/SSCS-6294
```
[ ] Yes
[X] No
```
=> SSCS-6294 Update layout of assign-case page

app/server/controllers/task-list.ts
Solving bug with hearingType on task-list page when MYA feature is ON
```
[ ] Yes
[ X ] No
```
=> Solving bug with hearingtype

app/server/controllers/task-list.ts, test/unit/controllers/task-list.test.ts
=> Enable coversheet pages

app/client/sass/_account-navigation.scss, locale/en.json, views/includes/account-navigation.html
https://tools.hmcts.net/jira/browse/SSCS-5907
Update survey links.
Fix navigation bar link
```
[ ] Yes
[X] No
```
=> SSCS-5907 - Update survey links.

app/client/sass/_account-navigation.scss, app/client/sass/_contact-include.scss, locale/en.json
https://tools.hmcts.net/jira/browse/SSCS-6343
Several frontend updates.
```
[ ] Yes
[X] No
```
=> SSCS-6343 - Fix ui issues

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/SSCS-6378
=> remove deprecated config

Jenkinsfile_nightly
=> commit change

locale/en.json
https://tools.hmcts.net/jira/browse/SSCS-6314
Match the address with cover sheet, confirmed with Rosie. 
```
[ ] Yes
[X] No
```
=> SSCS-6314 Fix address across mya.

app/server/app-configurations.ts, test/unit/app-configurations.test.ts
https://tools.hmcts.net/jira/browse/SSCS-6478
Fix History tab rendering issue, add missing nunjucks filter.
```
[ ] Yes
[X] No
```
=> Fix date filtering for paper cases.

infrastructure/main.tf
Add whitelisted infra module.
```
[X] Yes
[ ] No
```
=> Change white listed module of infra.

infrastructure/main.tf
Fix redis module for infra
```
[X] Yes
[ ] No
```
=> Fix redis module for infra.

app/server/app.ts, app/server/middleware/csrf.ts, package.json, test/page-objects/base.ts, test/unit/client/evidence-upload.test.ts, views/additional-evidence/evidence-options.html, views/additional-evidence/evidence-statement.html, views/additional-evidence/evidence-upload.html, views/assign-case/index.html, views/extend-deadline/confirmation-form.html, views/hearing-confirm/index.html, views/hearing-why/form.html, views/includes/csrf-hidden-input.html, views/login.html, views/question/answer-form.html, views/question/upload-evidence.html, views/submit-question.html, views/tribunal-view-confirm.html, views/tribunal-view.html, yarn.lock
https://tools.hmcts.net/jira/browse/SSCS-6598
Added csrf token check to prevent cross site forgery.
```
[X] Yes
[ ] No
```
=> Sscs 6508 csrf path limited

app/server/app.ts, app/server/middleware/csrf.ts, package.json, test/page-objects/base.ts, test/unit/client/evidence-upload.test.ts, views/additional-evidence/evidence-options.html, views/additional-evidence/evidence-statement.html, views/additional-evidence/evidence-upload.html, views/assign-case/index.html, views/extend-deadline/confirmation-form.html, views/hearing-confirm/index.html, views/hearing-why/form.html, views/includes/csrf-hidden-input.html, views/login.html, views/question/answer-form.html, views/question/upload-evidence.html, views/submit-question.html, views/tribunal-view-confirm.html, views/tribunal-view.html, yarn.lock
- https://tools.hmcts.net/jira/browse/SSCS-6598
- Added csrf token check to prevent cross site forgery.
```
[X] Yes
[ ] No
```
=> Adding csrf token to every form element.

infrastructure/aat.tfvars
turn on mya in aat
```
[ ] Yes
[x] No
```
=> turn on in aat

README.md
=> Update README.md with how to run locally

README.md
=> add log in details using tya param

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/SSCS-6853
```
[ ] Yes
[x] No
```
=> Added central appinsights

app/server/controllers/assign-case.ts
=> SSCS-6921 Postcode REGEX on MYA is too strong

infrastructure/main.tf
=> fix node version on ASE

charts/sscs-cor-frontend/requirements.yaml, charts/sscs-cor-frontend/values.preview.template.yaml, charts/sscs-cor-frontend/values.yaml
=> fixing idam-pr condition

locale/en.json, views/additional-evidence/evidence-options.html
=> SSCS-7200: Content changes to Write your statement page

Jenkinsfile_nightly
=> Added security scan and updated test url

locale/en.json
=> SSCS-7136 postcode content changes

app/server/app-configurations.ts, charts/sscs-cor-frontend/Chart.yaml, charts/sscs-cor-frontend/values.yaml, views/includes/head.html, views/layout.html
https://tools.hmcts.net/jira/browse/SSCS-7253
=> add environment global var to use it for the GA

Jenkinsfile_CNP, package.json, yarn.lock
=> disable ASE deployment

Jenkinsfile_CNP
=> Fix uglify issue

app/client/sass/_status-bar.scss, views/components/status-bar.html
https://tools.hmcts.net/jira/browse/SSCS-7172
Remove '--' from .leg selector so IE11 will recognize it.
```
[ ] Yes
[X ] No
```
=> Remove '--' before leg selector for IE11

app/server/app-insights.ts, app/server/controllers/additional-evidence.ts, app/server/controllers/login.ts, test/unit/controllers/additional-evidence.test.ts, test/unit/controllers/login.test.ts
https://tools.hmcts.net/jira/browse/SSCS-7303
Adding some AppInsights logging
* upon sign in
* upon providing a statement
* upon submitting uploaded files as evidence
* don't try to log if there is no client for app insights
```
[ ] Yes
[X] No
```
=> SSCS-7303 MYA – Add better logging into the MYA journey

app/client/javascript/detailsToggle.ts, test/unit/client/detailsToggle.test.ts, test/unit/client/evidence-upload.test.ts
https://tools.hmcts.net/jira/browse/SSCS-7173
Remove _role='group'_ attribute from details component so its state can be identified by screen readers
```
[ ] Yes
[ X] No
```
=> Sscs 7173 expandable content

locale/en.json, views/your-details.html
https://tools.hmcts.net/jira/browse/SSCS-7177
Add guards to display 'Not provided' if any of the user details are undefined
```
[ ] Yes
[X ] No
```
=> Add 'Not provided' default for empty cells

app/server/controllers/additional-evidence.ts, locale/en.json, test/unit/controllers/additional-evidence.test.ts, views/additional-evidence/index.html
https://tools.hmcts.net/jira/browse/SSCS-7287
- Pass pageTitleError flag from postEvidenceStatement controller
- Update errorPageTitle text in en.json
```
[ ] Yes
[ X] No
```
=> Pass pageTitleError flag from controller and update en.json

views/layout.html
https://tools.hmcts.net/jira/browse/SSCS-7344
Change govukPhaseBanner from alpha to beta
```
[ ] Yes
[X ] No
```
=> Change govukPhaseBanner from alpha to beta

README.md
=> Reademe update after migration of sscs-cor backend service to tribunal

app/server/app-insights.ts, app/server/controllers/login.ts, test/unit/controllers/login.test.ts
https://tools.hmcts.net/jira/browse/SSCS-7635
```
[ ] Yes
[ ] No
```
=> SSCS-7635 Add login App Insight Metrics

app/server/routes.ts, locale/en.json, views/redirect-mya.html
https://tools.hmcts.net/jira/browse/SSCS-7786
Pass the TYA number query parameter into login and register links correctly
```
[ ] Yes
[X] No
```
=> SSCS-7786 Pass TYA number correctly from static landing page

audit.json
=> updated audit.json to fix nightly build

audit.json
=> added url to fix security scan

Jenkinsfile_nightly, package.json
=> SSCS-7890- added config for full fuctional test

security.sh
=> updated High to Medium

audit.json
=> updated urls in audit.json

audit.json
=> updated more urls

audit.json
=> Ignore urls

audit.json
=> ignore welsh url

test/browser/2-0-additional-evidence.test.ts, test/browser/6-mya.test.ts
=> Include tests for provide evidence functionality and accessibility checks

app/server/controllers/assign-case.ts, app/server/controllers/hearing.ts, app/server/controllers/login.ts, test/unit/controllers/assign-case.test.ts, test/unit/controllers/hearing.test.ts, test/unit/controllers/login.test.ts
https://tools.hmcts.net/jira/browse/SSCS-7775
```
[ ] Yes
[X] No
```
=> SSCS-7775: MYA - status and hide hearing details for Adjourn hearings

audit.json, test/browser/2-0-additional-evidence.test.ts, test/browser/6-mya.test.ts, test/page-objects/additional-evidence-coversheet.ts
=> Tests for hearing tab, coversheet navigation

audit.json
=> update audit file

audit.json, test/browser/2-0-additional-evidence.test.ts, test/page-objects/additional-evidence-coversheet.ts
=> update navigation for tests

package.json, test/smoke/smoke-mya.test.ts
=> Add smoke tests for MYA

audit.json
=> update audit links

audit.json
=> fix security scan

app/core/tyaNunjucks.js, app/server/controllers/idam-stub.ts
=> SSCS-8358 - Major Sonar bug

app/server/controllers/idam-stub.ts
SSCS-8358 - Fix Major bug
Fix sonar [bug](https://sonarcloud.io/project/issues?id=SSCSCOR&open=AXWOn9_ctgwF3nOejKkc&resolved=false&sinceLeakPeriod=true&types=SECURITY_HOTSPOT)
=> SSCS-8358 - Fix Major bug

charts/sscs-cor-frontend/Chart.yaml, charts/sscs-cor-frontend/requirements.yaml
=> upgrade nodejs chart

app/server/controllers/additional-evidence.ts, app/server/controllers/assign-case.ts, app/server/controllers/decision.ts, app/server/controllers/extend-deadline.ts, app/server/controllers/hearing-confirm.ts, app/server/controllers/hearing-why.ts, app/server/controllers/hearing.ts, app/server/controllers/history.ts, app/server/controllers/login.ts, app/server/controllers/question.ts, app/server/controllers/questions-completed.ts, app/server/controllers/status.ts, app/server/controllers/submit-question.ts, app/server/controllers/task-list.ts, app/server/controllers/tribunal-view-accepted.ts, app/server/controllers/tribunal-view-confirm.ts, app/server/controllers/tribunal-view.ts, app/server/controllers/your-details.ts, app/server/services/additional-evidence.ts, app/server/services/question.ts, app/server/services/request-wrapper.ts, package.json, test/unit/controllers/questions-completed.test.ts, test/unit/controllers/submit-question.test.ts, test/unit/controllers/task-list.test.ts, test/unit/routes.test.ts, yarn.lock
https://tools.hmcts.net/jira/browse/SSCS-8356
```
[ ] Yes
[ ] No
```
=> SSCS-8356:Security Hotspot error to fix in MYA

test/browser/8-representative.mya.test.ts, test/fixtures/ccd.ts
=> added representative mya test

locale/content.json, test/browser/6-mya.cy.test.ts, test/browser/6-mya.test.ts, test/browser/7-mya-jp.test.ts, test/browser/8-representative.mya.test.ts, views/components/mya-contact-us.html
=> SSCS-8346/7 English/Welsh contact us updates

security.sh
=> Add env variables in security script

audit.json
=> Include urls in audit

audit.json
=> more false positive urls

locale/content.json, test/browser/6-mya.test.ts, test/browser/7-mya-jp.test.ts, test/browser/8-representative.mya.test.ts, views/components/mya-contact-us.html
=> SSCS-8590 - Update English Contact Times

charts/sscs-cor-frontend/Chart.yaml
=> SSCS-8694 Upgrade Helm

audit.json
=> fixed sec scan

audit.json
=> more false positive ignores

app/server/controllers/additional-evidence.ts, test/unit/controllers/additional-evidence.test.ts
=> SSCS-8673 Log upload file hash

app/server/utils/fieldValidation.ts, locale/content.json, test/unit/utils/field-validation.test.ts
https://tools.hmcts.net/jira/browse/SSCS-8679
regex for evidence description
```
[ ] Yes
[x] No
```
=> sscs 8679 regex

views/includes/head.html, views/layout.html
=> SSCS-8796 Update GTM

test/crossbrowser/journeys/myaLandingPage.test.js, test/crossbrowser/pages/additional-evidence/uploadEvidence.js
=> Fix failing cross browser tests on Edge and firefox

audit.json
=> ignore false negatives

app/server/controllers/av-evidence.ts, app/server/middleware/ensure-authenticated.ts, app/server/paths.ts, app/server/routes.ts, app/server/services/tyaService.ts, locale/content.json, test/mock/tribunals/data/oral/av-evidence.json, test/unit/controllers/av-evidence.test.ts, test/unit/middleware/ensure-authenticated.test.ts, test/unit/services/tyaService.test.ts, views/av-evidence-tab.html
https://tools.hmcts.net/jira/browse/SSCS-8742
=> SSCS-8742:View Audio/Video Evidence Link - MYA

app/server/app-configurations.ts
https://tools.hmcts.net/jira/browse/SSCS-8831
Added google analytics urls to content security policy for connectSrc
```
[ ] Yes
[x] No
```
=> sscs 8831 add google analytics to connectSrc

test/browser/teardown.ts, test/crossbrowser/helpers/TeardownHelper.js, test/crossbrowser/journeys/myaLandingPage.test.js, test/crossbrowser/pages/setup/authentication.js, test/crossbrowser/saucelabs.conf.js, test/fixtures/sidam.ts
https://tools.hmcts.net/jira/browse/SSCS-8891
Delete test users created as part of cross browser and functional tests
=> Added cross browser tests created users should be  deleted

test/browser/6-mya.test.ts, test/page-objects/appeal-details.ts, test/page-objects/status.ts
https://tools.hmcts.net/jira/browse/TA-539
- The only page that isn't exposed to the sscs-cor-frontend tests is the /your-details page. There should be a scenario that verifies this page.
- Also includes a test to touch the AV Evidence tab page.
```
[ ] Yes
[x] No
```
=> TA-539 Added Appeal details and AV Evidence tests

test/crossbrowser/pages/status/verifyStatusHeader.js
=> Fix MYA cross browser tests

locale/content.json, views/additional-evidence/evidence-confirm.html, views/additional-evidence/evidence-upload.html
https://tools.hmcts.net/jira/browse/SSCS-9018
change content
```
[ ] Yes
[x] No
```
=> sscs 9018 changed the content for uploading audio video

test/browser/6-mya.cy.test.ts
https://tools.hmcts.net/jira/browse/TA-626
1. CY - Navigate to Audio/Video Evidence tab'
2. CY - Navigate to Appeal Details page
3. CY - Hearing Tab
```
[ ] Yes
[ x] No
```
=> TA-626-Welsh Appeal Details-Audio-video-tab scenarios

package.json, test/browser/2-0-additional-evidence.test.ts, test/browser/6-mya.test.ts, test/browser/7-jointParty.cy.test.ts, test/browser/7-mya-jp.test.ts
https://tools.hmcts.net/jira/browse/TA-632
https://tools.hmcts.net/jira/browse/TA-631
1. Join Party Manage Your Appeal Scenarios
2. Joint Party Status Page
3. Nightly Pipeline tag update
```
[ ] Yes
[ x] No
```
=> TA-631- Welsh Joint Party Manage Your Appeal Scenarios

test/browser/2-0-additional-evidence.cy.test.ts, test/browser/2-0-additional-evidence.test.ts
https://tools.hmcts.net/jira/browse/TA-633
1.  Welsh Additional Evidence Scenarios
```
[ ] Yes
[x ] No
```
=> TA-633-Welsh-Additional Evidence Scenarios

locale/content.json, views/additional-evidence/evidence-confirm.html
https://tools.hmcts.net/jira/browse/SSCS-8779
Attendance allowance content
```
[ ] Yes
[x] No
```
=> sscs 8779 updated content

views/additional-evidence/evidence-confirm.html
https://tools.hmcts.net/jira/browse/SSCS-9018
Tidying up a closed ticket
```
[ ] Yes
[x] No
```
=> Sscs 9018 flag for av content

package.json
=> Add dependency version on resolution

package.json, yarn.lock
=> Fix dc failures

locale/content.json
=> SSCS-8786 - Bereavement Benefit on MYA Landing page

views/select-case.html
=> SSCS-9185: attendanceAllowance shown on MYA Home Screen

audit.json
Ticket raised here to fix the warnings https://tools.hmcts.net/jira/browse/SSCS-9196
```
[ ] Yes
[ ] No
```
=> Suppress warnings

audit.json
=> add few more urls to suppress list

test/crossbrowser/journeys/myaLandingPage.test.js, test/crossbrowser/pages/additional-evidence/uploadEvidence.js, test/crossbrowser/pages/postcode/verifyAppeallantPostCode.js, test/crossbrowser/saucelabs.conf.js
=> Add Safari browser to XB MYA test suite

package.json, yarn.lock
=> Upgrade browserlist package version

locale/content.json
=> SSCS-8815: IIDB (MYA)- Update: MYA Landing page

app/server/controllers/additional-evidence.ts, app/server/services/additional-evidence.ts, locale/content.json, test/unit/controllers/additional-evidence.test.ts
https://tools.hmcts.net/jira/browse/SSCS-9035
```
[ ] Yes
[x ] No
```
=> SSCS-9035:Handle evidence upload error on screen

package.json, yarn.lock
=> Update dependency package version

locale/content.json
=> Sscs 8826 jsa mya page

package.json, yarn.lock
=> Update dependency version

audit.json
=> suppress warnings related to aat

audit.json
=> Suppress security warnings related to AAT

Jenkinsfile_CNP, app/server/services/idam.ts, charts/sscs-cor-frontend/values.preview.template.yaml
SSCS-9127 - Remove redirect urls from IDAM AAT
=> SSCS-9127 - Remove redirect urls from IDAM AAT

app/server/controllers/login.ts, locale/content.json
https://tools.hmcts.net/jira/browse/SSCS-8954
```
[ ] Yes
[ ] No
```
=> SSCS-8954:Maternity Allowance (MYA)- Update: MYA Landing page

audit.json
=> Suppress idam warnings

app/client/javascript/evidence-upload.ts, locale/content.json, views/additional-evidence/evidence-confirm.html, views/additional-evidence/evidence-upload.html, views/file-selected-modal.html, views/includes/account-navigation.html, views/includes/header.html, views/layout.html
https://tools.hmcts.net/jira/browse/SSCS-9236
Content and modal for one file at a time
```
[ ] Yes
[x] No
```
=> sscs 9236 recreating PR

audit.json
=> Suppress warnings - ticket created to address SSCS-9180

audit.json
=> include urls to suppress

audit.json
=> suppress security warnings

audit.json
=> Suppress informational warnings

locale/content.json
https://tools.hmcts.net/jira/browse/SSCS-9065
=> SSCS-9065 Social fund content

locale/content.json
SSCS-8806 - Income Support MYA Landing Page
=> SSCS-8806 - Income Support MYA Landing Page

app/client/sass/_navigation-tabs.scss, views/components/navigation-tabs.html
https://tools.hmcts.net/jira/browse/SSCS-9257
Addition of new tabs are displayed in new line. Resolved with GDS design for tabs
```
[ ] Yes
[ x] No
```
=> SSCS-9257: Scrollable tabs

views/hearing-tab.html
https://tools.hmcts.net/jira/browse/SSCS-9344
```
[ ] Yes
[ x] No
```
=> SSCS-9344: Hearing date and time checks for empty value

audit.json
=> Suppress warnings which are addressed in a ticket

audit.json
=> more low/informational warnings suppressed

locale/content.json
SSCS-9212  - BSPS
SSCS-9277 - IDB
SSCS-9285 - Pension Credits
SSCS-9353 - Retirement Pension
=> SSCS-9212, SSCS-9277, SSCS-9285, SSCS-9353 - Update Mya landing page

locale/content.json
https://tools.hmcts.net/jira/browse/SSCS-9227
translations
```
[ ] Yes
[x] No
```
=> sscs 9227 welsh translation

audit.json
=> suppress low and informational warnings

audit.json
=> Suppress warning and created a ticket for a fix  SSCS-9476

audit.json, package.json, yarn.lock
=> fix dependency issues

app/client/sass/_navigation-tabs.scss, views/components/navigation-tabs.html
https://tools.hmcts.net/jira/browse/SSCS-9447
```
[ ] Yes
[ x] No
```
=> SSCS-9447:Selected Tab display modified

charts/sscs-cor-frontend/Chart.yaml, package.json, yarn.lock
trying new version of node
```
[ ] Yes
[x] No
```
=> SSCS-9464 new nodejs

locale/content.json
SSCS-9506 - Change Benefit name to Jobseeker’s Allowance (JSA)
=> SSCS-9506 - Change Benefit name to Jobseeker’s Allowance (JSA)

locale/content.json
https://tools.hmcts.net/jira/browse/SSCS-9502
```
[ ] Yes
[ ] No
```
=> SSCS-9502: Change Benefit name from Pension Credits to Pension Credit

audit.json
=> suppress low warnings

audit.json, package.json, yarn.lock
=> upgrade tar package

locale/content.json, views/additional-evidence/evidence-confirm.html
https://tools.hmcts.net/jira/browse/SSCS-9669
https://tools.hmcts.net/jira/browse/SSCS-9670
added content about audio/video being deleted if not admitted
```
[ ] Yes
[ ] No
```
=> sscs 9669 added warning about deleted content

audit.json
=> supress low warnings

package.json, yarn.lock
=> Upgrade dependency version

app/server/middleware/health.ts, config/default.json
https://tools.hmcts.net/jira/browse/SSCS-9672
```
[ ] Yes
[x ] No
```
=> SSCS-9672: Modify health check timeout

package.json, yarn.lock
=> upgrade json-schema version

test/browser/3-0-hearing-recording-request.cy.test.ts, test/browser/3-0-hearing-recording-request.test.ts
=> increse timout of select field

app/server/app-configurations.ts, locale/content.json, views/layout.html, views/policy-pages/cookie-privacy-new.html
https://tools.hmcts.net/jira/browse/SSCS-9684
```
[ ] Yes
[ x] No
```
=> SSCS-9684:New cookie page welsh content added

audit.json
=> suppress low security warnings

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/SSCS-9879
```
[ ] Yes
[x ] No
```
=> SSCS-9879: Upgrade properties-volume dependency

app/server/controllers/your-details.ts, locale/content.json, test/mock/cor-backend/services/citizen-assign-hearing.js, test/mock/cor-backend/services/citizen.js, test/mock/cor-backend/services/get-citizen.js, test/mock/tribunals/data/oral/activeAndDormantCases.json, test/unit/controllers/your-details.ts, views/your-details.html
https://tools.hmcts.net/jira/browse/SSCS-9824
```
[ ] Yes
[ ] No
```
=> SSCS-9824: Child Support - MYA: Other party Log in

locale/content.json, views/policy-pages/cookie-privacy-new.html
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/SSCS-9857
Change description
Update “Save” button on Welsh cookie policy page
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[ X] No
=> Update “Save” button on Welsh cookie policy page

locale/content.json
https://tools.hmcts.net/jira/browse/SSCS-9829
```
[ ] Yes
[ ] No
```
=> SSCS-9829 SSCS5 - Update: MYA Landing page

package.json, yarn.lock
=> Upgrade dependency package version

package.json, yarn.lock
=> upgrade npm package

audit.json
=> suppress medium warnings

app/server/data/appealStages.ts, views/components/status-bar.html, views/status-tab.html
=> SSCS-9953: SSCS5 - Update: MYA - HMRC

package.json, yarn.lock
=> Upgrade dependency pacakge version

locale/content.json, test/browser/2-0-additional-evidence.test.ts, test/page-objects/additional-evidence-upload-audio.ts, test/page-objects/additional-evidence.ts
=> Enable tests for splitting audio and document file upload in MYA

audit.json
=> suppress false positives

package.json
https://tools.hmcts.net/jira/browse/SSCS-10324
```
[ ] Yes
[x ] No
```
=> SSCS-10324-upgrade-minimist

audit.json
=> Fixing Nightly Build

audit.json
=> Fixing Security Scan

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/SSCS-10443
tagging added to Azure resources.
```
[ ] Yes
[X] No
```
=> Tagging added

infrastructure/main.tf
Reverts hmcts/sscs-cor-frontend#863
=> Revert "Tagging added"

audit.json
https://tools.hmcts.net/jira/browse/SSCS-10495
Supressions
```
[ ] Yes
[x] No
```
=> SSCS-10495-fix-nightly : add suppressions for security scan

Jenkinsfile_nightly
=> Disable fortify scan in nightly until secops-1839 is fixed

infrastructure/state.tf
https://tools.hmcts.net/jira/browse/SSCS-10443
Terraform Azure Provider update to 3.6.0
```
[ ] Yes
[X] No
```
=> sscs-10443-AzProviderUpdate

.gitignore, infrastructure/main.tf
https://tools.hmcts.net/jira/browse/SSCS-10443
Tagging added to key vault secrets
```
[ ] Yes
[X] No
```
=> SSCS-10443-InfraTaggingUpdate

audit.json
=> Fixing Security Scan: updating audit.json

infrastructure/main.tf, locale/content.json, test/browser/6-mya.test.ts, test/browser/7-mya-jp.test.ts, test/browser/8-representative.mya.test.ts
=> Update SSCS opening hours

audit.json
=> Suppress false warnings

audit.json
=> suppress zap warnings

charts/sscs-cor-frontend/Chart.yaml
sscsBaseChartUpdate-NodeJs245
```
[ ] Yes
[ ] No
```
=> sscsBaseChartUpdate-NodeJs245

audit.json
=> more zap suppressions

.gitignore, infrastructure/main.tf
SSCS-11008
Add content type and tags to secrets
```
[ ] Yes
[ x ] No
```
=> SSCS-11008 - Add content type and tags to secrets

app/server/controllers/assign-case.ts, app/server/controllers/hearing.ts, app/server/controllers/login.ts, app/server/utils/hearingUtils.ts, test/unit/controllers/assign-case.test.ts, test/unit/controllers/hearing.test.ts, test/unit/controllers/login.test.ts, test/unit/utils/hearingUtils.test.ts
https://tools.hmcts.net/jira/browse/SSCS-11227
```
[ ] Yes
[x] No
```
=> SSCS-11227 Correctly Hide Hearings

package.json, yarn.lock
=> Vunerablity fixes

charts/sscs-cor-frontend/Chart.yaml, package.json
=> SSCS-11390 Adding resolutions for security vulnerability

infrastructure/main.tf
=> removing old redis setup. direct to new one

config/aat.json
Turn off sameSite and httpOnly cookie flags in aat
=> SSCSCI-576 - Turn off flags

config/aat.json
Turn on sameSite and httpOnly cookie flags in aat
=> SSCSCI-576 - Turn on flags

config/aat.json, test/page-objects/base.ts
=> SSCSCI-576 - turn off AAT cookie flags

config/aat.json
=> SSCSCI-576 - Turn on AAT cookie flags

app/server/app.ts, app/server/middleware/session.ts, config/aat.json, config/preview.json
https://tools.hmcts.net/jira/browse/SSCSCI-576
Set the sameSite cookie setting to 'lax' to test if it is required for Oauth Redirect under a feature flag.
=> SSCSCI-576 - Set sameSite cookie setting to Lax

app/server/app-configurations.ts, app/server/app.ts, app/server/middleware/session.ts, app/server/utils/featureEnabled.ts, config/custom-environment-variables.json, config/default.json
Remove feature toggle for sameSite and secure cookies and Jquery
=> SSCSCI-767: Remove Jquery and Cookie Toggles

infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/SSCSCI-496
=> Use Basic subscription for redis cache in non-prod environments

test/browser/6-mya.cy.test.ts
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
=> SSCSCI-1539: correct static brittle assertion

test/browser/6-mya.cy.test.ts, test/browser/6-mya.test.ts, test/browser/7-jointParty.cy.test.ts, test/browser/7-mya-jp.test.ts, test/browser/8-representative.mya.cy.test.ts, test/browser/8-representative.mya.test.ts, test/browser/common.ts
- See [SSCSCI-1539](https://tools.hmcts.net/jira/browse/SSCSCI-1539)
- fixing nightly pipeline
- nightly-dev pipeline is green
=> Nightly dev

test/browser/6-mya.cy.test.ts
https://tools.hmcts.net/jira/browse/SSCSCI-1388
=> SSCSCI-1388: Nightly pipeline fixes

test/browser/6-ibc-mya.test.ts, test/browser/bootstrap.ts, test/browser/common.ts, test/fixtures/ccd.ts, test/fixtures/iba_payload.json, test/page-objects/base.ts, test/page-objects/status.ts
IBCA E2E Journey To Map and check the relevant IBCA text changes and appeal mappings for appellant - ENGLISH
This commit has a test that checks for the following:
Status Tab and Text For Appeal Received as per SSCSCI-1223.
Check the Contact Us Links for the new IBCA Contact Details as per SSCSCI-1225.
Check all the Help Pages Text changes with an IBCA Perspective as per SSCSCI-1224.
Case List Page  Changes to the text and Banner as per SSCSCI-1222.
[SSCSCI-1515](https://tools.hmcts.net/jira/browse/SSCSCI-1515)
IBCA E2E Journey To Map and check the relevant IBCA text changes and appeal mappings for appellant - ENGLISH
This commit has a test that checks for the following:
Status Tab and Text For Appeal Received as per SSCSCI-1223.
Check the Contact Us Links for the new IBCA Contact Details …
=> SSCSCI-1515: MYA : MVP - Automation - English.

charts/sscs-cor-frontend/Chart.yaml, package.json, yarn.lock
See [SSCSCI-1752](https://tools.hmcts.net/jira/browse/SSCSCI-1752)
Updated nodejs-chart to version 3.2.0. [This release uses the new OCI endpoint.](https://github.com/hmcts/chart-nodejs/releases/tag/v3.2.0) Also patched @hmcts/nodejs-healthcheck from 1.8.4 to 1.8.5
=> SSCSCI-1752: helm chart update

test/browser/common.ts
https://tools.hmcts.net/jira/browse/SSCSCI-1598
change expected banner height for welsh contact us
=> SSCSCI- nightly fix
