app/assets/sass/_question.scss, app/views/includes/sending-evidence.html, app/views/question.html, package.json, test/mock/data/question.js
* assuming that line-breaks are returned from the API as `\n`
* adding line breaks to mock data that is also used for creating a real question in functional testing
* applying two-thirds grid layout to sending evidence content
=> [PREVIEW] Using white-space pre-wrap to retain line breaks in question body

.eslintrc.json, app/assets/sass/_task-list.scss, app/assets/sass/application.scss, app/controllers/login.js, app/controllers/question.js, app/controllers/taskList.js, app/locale/en.json, app/middleware/ensure-authenticated.js, app/routes.js, app/services/getOnlineHearing.js, app/utils/fieldValidation.js, app/views/login.html, app/views/task-list.html, paths.js, test/.eslintrc.json, test/browser/common.js, test/browser/health.test.js, test/browser/question.test.js, test/browser/task-list.test.js, test/mock/services/hearing.js, test/unit/controllers/login.test.js, test/unit/controllers/question.test.js, test/unit/controllers/taskList.test.js, test/unit/middleware/ensure-authenticated.test.js, test/unit/middleware/error-handler.test.js, test/unit/middleware/health.test.js, test/unit/middleware/session.test.js, test/unit/services/getOnlineHearing.test.js, test/unit/utils/fieldValidation.test.js
Adding a simple login page which asks for email address only. This enables us to ask the backend for the online hearing ID, name and case reference.
This login page is a temporary solution until IDAM is implemented for user registration and sign-in.
When using the login page with an email address associated with a case in CCD it should now display the associated name and case reference.
At this stage, the app still functions as it previously did, allowing you to go directly to a task-list for an online hearing by adding it as a query parameter. This should be removed in a later iteration once we have a solution for functionally testing the sign-in and retrieve online hearing relating to an appeal in CCD!
I would like to add some browser tests to cover the login functionality, which would …
=> [PREVIEW] SSCS-3554 show appellant name and SC reference

app/server/controllers/question.ts, app/server/controllers/submit_question.ts, app/server/controllers/taskList.ts, app/server/routes.ts, app/server/views/question.html, package.json, test/browser/1-task-list.test.ts, test/browser/2-question.test.ts, test/browser/common.ts, test/fixtures/coh.js, test/mock/services/allQuestions.js, test/mock/services/answer.js, test/mock/services/question.js, test/mock/services/questionData.js, test/mock/services/sumbit_answer.js, test/page-objects/base.js, test/page-objects/question.js, test/unit/controllers/question.test.ts, test/unit/controllers/submit_question.test.ts, yarn.lock
* adding simple state to mock backend e.g. keeping track of question answer state
* no longer cache any dyson stubs as they are not deterministic anymore
* this is to facilitate more complex functional testing
* protecting all routes behind "auth", from now you must have a valid case in CCD and "login" using the associated email address
* removing use of hearing ID in task list URL, it is held in the redis session after successfully signing in with an email address
* adding extra tests now possible due to having simple state in the stub backend
=> [PREVIEW] SSCS-3554 More functional testing and enforcing "login"

app/server/controllers/question.ts, app/server/controllers/questions-completed.ts, app/server/controllers/submit_question.ts, app/server/controllers/taskList.ts, app/server/locale/en.json, app/server/paths.js, app/server/routes.ts, app/server/views/includes/sending-evidence-contact-details.html, app/server/views/question.html, app/server/views/questions-completed.html, app/server/views/submit-question.html, app/server/views/task-list.html, package.json, test/browser/2-question.test.ts, test/browser/bootstrap.ts, test/fixtures/coh.js, test/page-objects/questions-completed.js, test/unit/controllers/question.test.ts, test/unit/controllers/questions-completed.test.ts, test/unit/controllers/submit_question.test.ts, test/unit/controllers/taskList.test.ts, yarn.lock
**Tidying up use of hearing ID and case reference**
* since we now enforce "login" using email address there is no need to get hearing ID from the querystring
* case reference will set in the session, a default is no longer required
**Displaying questions completed page when all questions are submitted**
* adding moment types
* amending submit question page to send user to new page if all questions are submitted
* at this stage, to be safe, the questions are requested from the backend when required
**Functional testing for questions completed page**
* adjusting tests to be aware of multiple questions
* COH data bootstrap now creates 3 questions to match local stubs
**Screenshot**
=> [PREVIEW] SSCS-3583 all questions submitted

app/server/controllers/question.ts, app/server/controllers/submit-question.ts, app/server/controllers/task-list.ts, app/server/routes.ts, app/server/services/getAllQuestions.ts, app/server/views/question/answer-form.html, app/server/views/submit-question.html, app/server/views/task-list.html, test/accessibility/runPa11y.ts, test/browser/1-task-list.test.ts, test/browser/3-question.test.ts, test/browser/bootstrap.ts, test/mock/cor-backend/services/all-questions.js, test/mock/cor-backend/services/question.js, test/page-objects/question.ts, test/page-objects/submit-question.ts, test/unit/controllers/question.test.ts, test/unit/controllers/submit-question.test.ts, test/unit/controllers/task-list.test.ts, test/unit/services/getAllQuestions.test.ts
* using question ordinal instead of question id
* store questions in session after retrieving from COH
* refresh questions in session after each request for `/task-list`
* if questions are not found in the session redirect the user back to the task list page
* adjusting all link/urls for questions to use the ordinal
=> [PREVIEW] Cleaner question urls

app/server/services/getAllQuestions.ts, test/mock/cor-backend/services/all-questions.js, views/task-list.html
* the issue came about because when questions are created in COH via JUI, the question ordinal is not incremented, therefore every question in the round has an ordinal of 1
* using the ordinal to drive the URLs for questions meant only the first question was accessible
* the fix is to still use the same URLs but to find the question in the list by index instead of `question_ordinal`
* the all questions mock was updated to reflect how this would be returned from the backend given the same ordinal being used for every question in COH
=> [PREVIEW] SSCS-4117 Fixing duplicate question URLs

app/server/controllers/question.ts, app/server/controllers/submit-question.ts, test/fixtures/coh.ts, test/unit/controllers/question.test.ts, test/unit/controllers/submit-question.test.ts
* the actual ordinal was being used for the answer form post, instead using the question index as ordinal
* no need to `parseInt` anymore
* adjusting COR backend stub to give incorrect ordinals as we would get from JUI entering questions
=> More fixes for question URLs using ordinals

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/SSCS-4136
This changes adds a simple Jenkinsfile_nightly config which will automatically run the NSP dependency checker, and results will be posted on Slack if the build fails ([or once it starts passing again](https://github.com/hmcts/cnp-jenkins-library/blob/5f476062bad590d081a9abe2755063d226f53421/README.md)).
```
[ ] Yes
[x] No
```
=> @SSCS-4136: adding basic overnight pipeline which will test dependencies

app/server/app-insights.ts, config/default.json, test/unit/app-insights.test.ts
* this is due to setting up a shared app insights for all SSCS services
* when viewing them, the logs can be filtered by cloud role name to limit them to a specific app
=> SSCS-3940 Adding cloud role name to app insights

app/server/controllers/question.ts, test/browser/3-question.test.ts, test/unit/controllers/question.test.ts
* removing validation from "Save for later" journey
* save the answer only if it's not empty
=> SSCS-4246 Displaying question as draft correctly

app/server/services/idam.ts, package.json, test/unit/services/idam.test.ts, yarn.lock
* unit tests have a more relaxed nock check but additional sinon spy check
* also removing from package.json and yarn.lock
=> SSCS-4166 Removing use of superagent in idam service

app/server/controllers/idam-stub.ts
* this changed after the service refactor
* multipart fields are now available via `req.body` using multer
=> Fixing the idam stub getToken function to handle multipart form post

app/client/javascript/evidence-upload.ts, test/unit/client/javascript/evidence-upload.test.ts
With JS enabled if the first file you uploaded was too big or not of
an acceptable type the page would reload but the evidence upload
checkbox was not ticked and the error message was hidden. Make
evidence upload section visable if you have uploaded files or have
an errors.
=> SSCS-4349 Allow JS evidence upload errors

Jenkinsfile_CNP
The PR builds use an AKS environment to run their functional tests. We do not
use this in AAT or prod and are not running the app locally with docker so do
not need to build the image.
=> Do not build docker images on master only PR builds

app/server/controllers/login.ts, views/question/answer-form.html, views/submit-question.html
User research has shown that the links to save you answer on the answer
page or go back to question on the submit confirmation page are not
being seen by users. Changed them to secondary buttons to make them
more visible. Also removed some logs in login as I think they will be
writing user details to the logs.
=> SSCS-4424 Changed links to secondary buttons

app/client/javascript/evidence-upload.ts, app/server/controllers/question.ts, test/browser/3-question.test.ts, test/page-objects/question.ts, test/unit/client/javascript/evidence-upload.test.ts, test/unit/controllers/question.test.ts, views/question/evidence-list.html
On the answer a question page if the user updated their answer and then either uploaded or deleted evidence the update to the answer was not being saved.
These cases have been fixed
- Upload evidence JS on.
- Upload evidence and there was an error (file too large or wrong type) JS on.
- Delete evidence JS on or off.
=> Sscs 4412 question answer not saved

README.md, create-s2s-header.ts, package.json, test/browser/bootstrap.ts, test/fixtures/coh.ts
If you need a pair of S2S headers then you can call
yarn test:create-s2s-headers
to create them. Full instructions in README.md
=> Add a way to get the S2S headers

app/server/app.ts, app/server/routes.ts, package.json, yarn.lock
Our other express apps make use of the Helmet module to add headers to
prevent clickjacking. Helmet also adds a number of other headers for
security reasons. Have
- Added all default helmet headers
- Added helmet content security policy headers
- Added helmet referrer policy
- Added the following as they are set in SYA and TYA
- X-Robots-Tag
- X-Served-By
- Cahce-Control
- Added endpoint for robots.txt
Issues added to make consistent with TYA and SYA but need to be
addressed
- Maybe we don't want to set the X-Served-By header as that shows the
os the app is running on.
- We don't want to have no cache on JS CCS images etc.
=> SSCS-4735 Clickjacking

app/server/app.ts
Added google domains to content security in Helmet Configuration, 
this is to enable  preview mode for google tag manager.
=> Edited helmet settings to support google tag manager preview mode.

test/page-objects/base.ts
- Adding try/catch blocks on BasePage methods that can throw exceptions
- If an exception is caught, take a screenshot with Puppeteer library
=> adding try/catch blocks on BasePage class

app/server/controllers/decision.ts, app/server/middleware/check-decision.ts, app/server/services/hearing.ts, test/mock/cor-backend/services/hearing.js, test/unit/controllers/decision.test.ts, test/unit/controllers/hearing-confirm.test.ts, test/unit/controllers/hearing-why.test.ts, test/unit/controllers/tribunal-view-confirm.test.ts, test/unit/controllers/tribunal-view.test.ts, test/unit/middleware/check-decision.test.ts, test/unit/routes.test.ts
When the final decision page was originally written we expected the COH
state to reflect the final decision. This has not been done so we have
added has_final_decision to the api call on the backend when loading a
hearing. This looks in the the appeals history to see if a final
decision has been issued. Use this to decide if we show the final
decision page.
=> SSCS-5230 Show final decision

views/tribunal-view.html
Updated the tables on the tribunal view when there is no daily living or
mobility activities.
=> SSCS-5218 Tables in tribunal view when empty

app/server/middleware/check-decision.ts, test/unit/middleware/check-decision.test.ts
In JUI the panel can issue a final decision without issuing a
preliminary view. COR could not handle this as it tries to parse
it as a Preliminary view and some of the data is not there. Update
routing to use the has_final_decision attribute of the hearing to
display the final decision screen.
=> SSCS-5230 View final decision when there is no Preliminary View

locale/en.json
The mapping was out of date when the panel had select 2 points for
budgeting activity.
=> SSCS-5221 Missing budget description in PV

test/integration/login.test.ts, views/decision.html
When we wrote this there was an idea that the appellant would see an
accepted or rejected decision. But if the panel rejects the appeal they
will relist it rather than show the appeal rejected here. Changed the
title of the decision page to be static as it no longer needs to
select between accepted and rejected and the states are not set anyway.
=> SSCS-3973 Decision title missing

app/server/controllers/additional-evidence.ts, locale/en.json, test/browser/1-task-list.test.ts, views/additional-evidence/evidence-options.html, views/additional-evidence/evidence-post.html, views/additional-evidence/evidence-statement.html, views/additional-evidence/evidence-upload.html, views/additional-evidence/index.html, views/task-list.html
https://tools.hmcts.net/jira/browse/SSCS-3565
Adding option to provide additional evidence on task-list page.
A link should redirect the appellant to a page with different options to send new evidence.
Evidence options are: 
- Write a statement online
- Upload a document
- Provide information to the appellant so he or she can send the evidence through the post 
```
[ ] Yes
[ X ] No
```
=> Providing additional evidence link and additional evidence landing page

app/server/controllers/assign-case.ts, app/server/routes.ts, test/unit/controllers/assign-case.test.ts
Previosly we were not loaidng the appeal when a case was assigned to a
user instead we were getting an error. Load the appeal after assigning
the case in the same way we do when we login and we have already
assigned the appeal.
https://tools.hmcts.net/jira/browse/SSCS-6062
```
[ ] Yes
[X] No
```
=> SSCS-6062 Load the appeal when assigning a case to a user

Dockerfile, acb.tpl.yaml, package.json, yarn.lock
Next monday we will be changing the registry the pipeline will be pushing to by default
the registry will be changing from:
hmcts => hmctspublic
you will no longer need to log in to pull your images (because it is a public registry, same as dockerhub)
the name of the "repo" will change from
"hmcts/product-component" => "product/component"
```
[ ] Yes
[ ] No
```
=> Updated docker hmcts public registry

app/server/utils/screenReaderUtils.ts, locale/en.json, test/unit/utils/screenReaderUtils.ts, views/includes/appellant-details.html
Currently MYA fails with an error if the case does not have an SC
number. This is an edge case as the appellant should not have got a link
to MYA until their case has an SC number but sometimes we will send one
out. The only issue was we spell out the sc number for screen readers
so made that function handle undefined and display 'to be confirmed' on
the page.
https://tools.hmcts.net/jira/browse/SSCS-6134
```
[ ] Yes
[X] No
```
=> SSCS-6134 Load MYA even if an SC number has been set

app/server/controllers/task-list.ts, app/server/services/additional-evidence.ts, test/unit/controllers/task-list.test.ts
Previously you had to have a hearing id to get a cover sheet. Now with
MYA you might not have a hearing ID. so need to create the coversheet
with the case id. Update the coversheet endpoint to take either a case
id or hearing id. As the case id is a long and the hearing id a GUUID
we can tell which we have been given.
https://tools.hmcts.net/jira/browse/SSCS-6098
```
[ ] Yes
[X] No
```
=> SSCS-6098 Update get coversheet endpoint

app/server/controllers/hearing.ts, app/server/middleware/ensure-authenticated.ts, test/unit/middleware/ensure-authenticated.test.ts, test/unit/routes.test.ts, views/components/navigation-tabs.html
https://tools.hmcts.net/jira/browse/SSCS-6259
Appellants in COR shouldn't be able to see Hearing Tab or even enter the page if they enter the url directly.
```
[ ] Yes
[ X ] No
```
=> Suppress hearing tab for appellants in COR

app/client/sass/application.scss, test/browser/1-task-list.test.ts, test/browser/6-mya.test.ts, test/page-objects/base.ts, views/includes/header.html
https://tools.hmcts.net/jira/browse/SSCS-6298
Signout link was reallocated from header to a new navigation bar only visible if MYA feature is active. Old signout link was removed from the original header and so appellants cant currently sign out. This PR fixes that and adds back the link so users are able to sign out.
```
[ ] Yes
[ X ] No
```
=> Adding back signout for non MYA

app/client/javascript/evidence-upload.ts, app/client/sass/_question.scss, app/client/sass/application.scss, test/unit/client/evidence-upload.test.ts, views/additional-evidence/evidence-upload.html
https://tools.hmcts.net/jira/browse/SSCS-7170
Amending file upload inputs to be included in the tab order
* this ensures that they are keyboard discoverable, but the appearance remains the same
* instead of not displaying the file input, it is made the same size and location as the label and hidden behind it using a z-index
```
[ ] Yes
[X] No
```
=> SSCS-7170 Fix file input keyboard discovery/focus

views/request-type/index.html, views/request-type/request-confirm.html
SSCS-9799 - confirmation after requesting a hearing recording
Success Message (moved text up and made it green):
Error Message (when tribunals is down is as before):
=> SSCS-9799 - confirmation after requesting a hearing recording
